export type ThemeMode = 'light' | 'dark' | 'midnight' | 'emerald' | 'rose';

let activeThemeMode: ThemeMode = 'dark';

export function setActiveThemeMode(mode: ThemeMode) {
  activeThemeMode = mode;
}

export function getActiveThemeMode(): ThemeMode {
  return activeThemeMode;
}

export const themePalettes = {
  light: {
    primary: '#10B981',
    primaryLight: '#34D399',
    primaryDark: '#059669',
    accent: '#F59E0B',
    accentLight: '#FBBF24',
    background: '#F9FAFB',
    surface: '#FFFFFF',
    surfaceAlt: '#F3F4F6',
    card: '#FFFFFF',
    cardBorder: '#E5E7EB',
    subtext: '#4B5563',
    text: '#111827',
    textSecondary: '#4B5563',
    textTertiary: '#9CA3AF',
    income: '#10B981',
    incomeLight: 'rgba(16, 185, 129, 0.1)',
    expense: '#EF4444',
    expenseLight: 'rgba(239, 68, 68, 0.1)',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    shadow: 'rgba(0, 0, 0, 0.05)',
    white: '#FFFFFF',
    black: '#000000',
  },
  dark: {
    primary: '#10B981',
    primaryLight: '#34D399',
    primaryDark: '#059669',
    accent: '#F59E0B',
    accentLight: '#FBBF24',
    background: '#090E17',
    surface: '#111A2E',
    surfaceAlt: '#1B253B',
    card: '#111A2E',
    cardBorder: '#1F293D',
    subtext: '#9CA3AF',
    text: '#F3F4F6',
    textSecondary: '#9CA3AF',
    textTertiary: '#6B7280',
    income: '#10B981',
    incomeLight: 'rgba(16, 185, 129, 0.15)',
    expense: '#EF4444',
    expenseLight: 'rgba(239, 68, 68, 0.15)',
    border: '#1F293D',
    borderLight: '#2D3A54',
    shadow: 'rgba(0, 0, 0, 0.3)',
    white: '#FFFFFF',
    black: '#090E17',
  },
  midnight: {
    primary: '#6366F1',
    primaryLight: '#818CF8',
    primaryDark: '#4F46E5',
    accent: '#FBBF24',
    accentLight: '#FDE047',
    background: '#0B0F19',
    surface: '#161E2E',
    surfaceAlt: '#243048',
    card: '#161E2E',
    cardBorder: '#1F293D',
    subtext: '#9CA3AF',
    text: '#F3F4F6',
    textSecondary: '#9CA3AF',
    textTertiary: '#6B7280',
    income: '#10B981',
    incomeLight: 'rgba(16, 185, 129, 0.15)',
    expense: '#EF4444',
    expenseLight: 'rgba(239, 68, 68, 0.15)',
    border: '#1F293D',
    borderLight: '#2D3A54',
    shadow: 'rgba(0, 0, 0, 0.4)',
    white: '#FFFFFF',
    black: '#05070B',
  },
  emerald: {
    primary: '#059669',
    primaryLight: '#34D399',
    primaryDark: '#047857',
    accent: '#F59E0B',
    accentLight: '#FBBF24',
    background: '#061B14',
    surface: '#0C2B21',
    surfaceAlt: '#143D30',
    card: '#0C2B21',
    cardBorder: '#123F32',
    subtext: '#8FA89B',
    text: '#E6F4EA',
    textSecondary: '#8FA89B',
    textTertiary: '#5F756B',
    income: '#10B981',
    incomeLight: 'rgba(16, 185, 129, 0.15)',
    expense: '#F43F5E',
    expenseLight: 'rgba(244, 63, 94, 0.15)',
    border: '#123F32',
    borderLight: '#1B5242',
    shadow: 'rgba(0, 0, 0, 0.4)',
    white: '#FFFFFF',
    black: '#030F0B',
  },
  rose: {
    primary: '#EC4899',
    primaryLight: '#F472B6',
    primaryDark: '#BE185D',
    accent: '#FB923C',
    accentLight: '#FDE047',
    background: '#0F0712',
    surface: '#1C0E24',
    surfaceAlt: '#2D173A',
    card: '#1C0E24',
    cardBorder: '#321B40',
    subtext: '#9CA3AF',
    text: '#FCE7F3',
    textSecondary: '#9CA3AF',
    textTertiary: '#6B7280',
    income: '#10B981',
    incomeLight: 'rgba(16, 185, 129, 0.15)',
    expense: '#EF4444',
    expenseLight: 'rgba(239, 68, 68, 0.15)',
    border: '#321B40',
    borderLight: '#4A2A5E',
    shadow: 'rgba(0, 0, 0, 0.4)',
    white: '#FFFFFF',
    black: '#08040A',
  },
};

const Colors = {
  get primary() { return themePalettes[activeThemeMode].primary; },
  get primaryLight() { return themePalettes[activeThemeMode].primaryLight; },
  get primaryDark() { return themePalettes[activeThemeMode].primaryDark; },
  get accent() { return themePalettes[activeThemeMode].accent; },
  get accentLight() { return themePalettes[activeThemeMode].accentLight; },
  get income() { return themePalettes[activeThemeMode].income; },
  get incomeLight() { return themePalettes[activeThemeMode].incomeLight; },
  get expense() { return themePalettes[activeThemeMode].expense; },
  get expenseLight() { return themePalettes[activeThemeMode].expenseLight; },
  get background() { return themePalettes[activeThemeMode].background; },
  get surface() { return themePalettes[activeThemeMode].surface; },
  get surfaceAlt() { return themePalettes[activeThemeMode].surfaceAlt; },
  get card() { return themePalettes[activeThemeMode].card; },
  get cardBorder() { return themePalettes[activeThemeMode].cardBorder; },
  get subtext() { return themePalettes[activeThemeMode].subtext; },
  get text() { return themePalettes[activeThemeMode].text; },
  get textSecondary() { return themePalettes[activeThemeMode].textSecondary; },
  get textTertiary() { return themePalettes[activeThemeMode].textTertiary; },
  get border() { return themePalettes[activeThemeMode].border; },
  get borderLight() { return themePalettes[activeThemeMode].borderLight; },
  get shadow() { return themePalettes[activeThemeMode].shadow; },
  get white() { return themePalettes[activeThemeMode].white; },
  get black() { return themePalettes[activeThemeMode].black; },

  // Backwards compatibility with standard React Navigation themes
  light: {
    text: '#111827',
    background: '#F9FAFB',
    tint: '#10B981',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: '#10B981',
  },
  dark: {
    text: '#F3F4F6',
    background: '#090E17',
    tint: '#10B981',
    tabIconDefault: '#6B7280',
    tabIconSelected: '#10B981',
  }
};

export default Colors;
