import { StyleSheet, Platform, Dimensions } from 'react-native';
import Colors from '@/constants/colors';

export const getStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 4,
  },
  sheetTitle: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 20,
    color: colors.text,
  },
  walletBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginHorizontal: 20,
    marginTop: 4,
    marginBottom: 4,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
    gap: 6,
  },
  walletBadgeText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  typeToggle: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    padding: 4,
    marginBottom: 20,
    marginTop: 8,
  },
  typeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 6,
  },
  typeBtnActiveExpense: {
    backgroundColor: colors.expense,
  },
  typeBtnActiveIncome: {
    backgroundColor: colors.income,
  },
  typeBtnActiveTransfer: {
    backgroundColor: '#3b82f6',
  },
  typeText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 15,
    color: colors.textSecondary,
  },
  typeTextActive: {
    color: colors.text,
  },
  amountSection: {
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  walletsScrollContent: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  walletChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 2,
    borderColor: 'transparent',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
  },
  walletChipText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 14,
    color: colors.textSecondary,
  },
  label: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  amountInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 16,
    paddingRight: 16,
    paddingLeft: 4,
    height: 72,
    gap: 12,
  },
  currencyTag: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  currencyTagCode: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 15,
  },
  currencyTagSymbol: {
    fontFamily: 'Cairo_400Regular',
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: -2,
  },
  amountInput: {
    flex: 1,
    fontFamily: 'Cairo_700Bold',
    fontSize: 32,
    color: colors.text,
  },
  calcTriggerBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  budgetWarningContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.expense + '12',
    borderWidth: 1,
    borderColor: colors.expense + '24',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 10,
    gap: 8,
  },
  budgetWarningText: {
    flex: 1,
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
    color: colors.expense,
    textAlign: 'left',
  },
  categorySection: {
    marginBottom: 20,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryItem: {
    width: '30%',
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 6,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  addCategoryItem: {
    borderColor: colors.primary + '30',
    borderStyle: 'dashed',
    backgroundColor: 'transparent',
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryName: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
    color: colors.text,
    textAlign: 'center',
  },
  descSection: {
    marginBottom: 16,
  },
  descInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    padding: 14,
    fontFamily: 'Cairo_400Regular',
    fontSize: 15,
    color: colors.text,
    minHeight: 60,
  },
  smartInputCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    marginBottom: 16,
  },
  smartCardHeader: {
    marginBottom: 8,
  },
  smartCardTitle: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 13,
  },
  smartInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    height: 48,
    gap: 6,
  },
  smartTextInput: {
    flex: 1,
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 13,
    paddingVertical: 0,
  },
  smartActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  micBtnActive: {
    backgroundColor: '#EF4444',
  },
  smartFeedbackPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
  },
  smartMessageText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
  },
  ocrScanningWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    paddingVertical: 6,
  },
  ocrScanningText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
  },
  receiptPreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  receiptThumb: {
    width: 44,
    height: 44,
    borderRadius: 6,
  },
  receiptAttachedText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
  },
  removeReceiptBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  removeReceiptText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 12,
  },
  ocrQuickBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  ocrQuickBannerText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 12,
  },
  dateTimeCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    marginBottom: 20,
  },
  dateTimeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  quickNowBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  quickNowBadgeText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 11,
  },
  dateTimeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dateTimePill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  dateTimePillSub: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 10,
    lineHeight: 13,
  },
  dateTimePillMain: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 13,
  },
  categorySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  showAllCatsBtn: {
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  showAllCatsText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 12,
  },
  collapsibleDetailsCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    marginBottom: 16,
  },
  collapsibleHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  collapsibleHeaderTitle: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 13,
  },
  detailsBadgeIndicator: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  detailsBadgeText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 10,
  },
  collapsibleContent: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  stickyBottomBar: {
    paddingHorizontal: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 8,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 14,
    gap: 8,
    marginBottom: 20,
  },
  saveText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 16,
    color: '#ffffff',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  datePickerSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    paddingBottom: 32,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  datePickerTitle: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 18,
    color: colors.text,
  },
  dateList: {
    paddingHorizontal: 16,
  },
  dateOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginVertical: 2,
  },
  dateOptionActive: {
    backgroundColor: colors.primary + '12',
  },
  dateOptionText: {
    fontFamily: 'Cairo_400Regular',
    fontSize: 15,
    color: colors.text,
  },
  dateOptionTextActive: {
    fontFamily: 'Cairo_600SemiBold',
    color: colors.primary,
  },
  // Calculator Modal styles
  calcSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 20,
  },
  calcHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calcTitle: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 18,
    color: colors.text,
  },
  calcConfirmBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary + '12',
  },
  calcDisplay: {
    backgroundColor: colors.surfaceAlt,
    padding: 20,
    alignItems: 'flex-end',
    height: 100,
    justifyContent: 'center',
    gap: 4,
  },
  calcExprText: {
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 22,
    color: colors.textSecondary,
  },
  calcResultText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 28,
    color: colors.text,
  },
  calcPad: {
    padding: 16,
    gap: 10,
  },
  calcRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  calcKey: {
    flex: 1,
    aspectRatio: 1.6,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calcKeyPressed: {
    opacity: 0.7,
  },
  calcKeyOp: {
    backgroundColor: colors.primary + '12',
  },
  calcKeyText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 20,
    color: colors.text,
  },
  calcKeyOpText: {
    color: colors.primary,
    fontSize: 22,
  },
  calcKeyClear: {
    backgroundColor: colors.expense + '15',
  },
  calcKeyClearText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 20,
    color: colors.expense,
  },
  calcKeyBackspace: {
    flex: 1,
    aspectRatio: 1.6,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calcKeyConfirm: {
    flex: 3,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calcKeyConfirmText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 18,
    color: colors.text,
  },
  // Custom Category Modal styles
  customCatSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '85%',
    flexDirection: 'column',
  },
  customCatBody: {
    padding: 20,
    paddingBottom: 30,
    gap: 16,
  },
  formGroup: {
    gap: 8,
  },
  modalInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 16,
    color: colors.text,
  },
  colorsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    paddingVertical: 6,
  },
  colorCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 6,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  modalFooter: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  modalSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  modalSaveText: {
    fontFamily: 'Cairo_700Bold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  recurringAlertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary + '10',
    marginHorizontal: 20,
    marginTop: 8,
    padding: 12,
    borderRadius: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.primary + '25',
  },
  recurringAlertText: {
    flex: 1,
    fontFamily: 'Cairo_600SemiBold',
    fontSize: 12,
    color: colors.primary,
    textAlign: 'left',
  },
});

export default getStyles;
